<?php
/**
 * ComponentApi
 * PHP version 5
 *
 * @category Class
 * @package  Exivo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * exivo api documentation
 *
 * The exivo API lets you manage an exivo site. To be allowed to use the API the Connection service needs to be activated. For every HTTP request the `siteId`, an `API_KEY` and the corresponding `API_SECRET` are required. All this information can be found in the [exivo app](https://customer.exivo.io/credentials). A new `API_KEY` can be generated in the app. Please note that `API_SECRET` is a confidential information and should be stored securely. After closing the dialogue or refreshing the page the secret can't be displayed anymore. If the secret is lost, a new key needs to be generated and the old must be deleted.
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Exivo\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Exivo\ApiException;
use Exivo\Configuration;
use Exivo\HeaderSelector;
use Exivo\ObjectSerializer;

/**
 * ComponentApi Class Doc Comment
 *
 * @category Class
 * @package  Exivo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ComponentApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getComponent
     *
     * get component by ID
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component to return (required)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Exivo\Model\Component
     */
    public function getComponent($site_id, $component_id)
    {
        list($response) = $this->getComponentWithHttpInfo($site_id, $component_id);
        return $response;
    }

    /**
     * Operation getComponentWithHttpInfo
     *
     * get component by ID
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component to return (required)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Exivo\Model\Component, HTTP status code, HTTP response headers (array of strings)
     */
    public function getComponentWithHttpInfo($site_id, $component_id)
    {
        $returnType = '\Exivo\Model\Component';
        $request = $this->getComponentRequest($site_id, $component_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exivo\Model\Component',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getComponentAsync
     *
     * get component by ID
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component to return (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getComponentAsync($site_id, $component_id)
    {
        return $this->getComponentAsyncWithHttpInfo($site_id, $component_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getComponentAsyncWithHttpInfo
     *
     * get component by ID
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component to return (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getComponentAsyncWithHttpInfo($site_id, $component_id)
    {
        $returnType = '\Exivo\Model\Component';
        $request = $this->getComponentRequest($site_id, $component_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getComponent'
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component to return (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getComponentRequest($site_id, $component_id)
    {
        // verify the required parameter 'site_id' is set
        if ($site_id === null || (is_array($site_id) && count($site_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $site_id when calling getComponent'
            );
        }
        // verify the required parameter 'component_id' is set
        if ($component_id === null || (is_array($component_id) && count($component_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $component_id when calling getComponent'
            );
        }

        $resourcePath = '/{siteId}/component/{componentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($site_id !== null) {
            $resourcePath = str_replace(
                '{' . 'siteId' . '}',
                ObjectSerializer::toPathValue($site_id),
                $resourcePath
            );
        }
        // path params
        if ($component_id !== null) {
            $resourcePath = str_replace(
                '{' . 'componentId' . '}',
                ObjectSerializer::toPathValue($component_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getComponentAccessLog
     *
     * get components access log
     *
     * @param  string $site_id ID of site to work (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     * @param  \DateTime $from e.g. \&quot;2013-10-22\&quot; (optional)
     * @param  \DateTime $to e.g. \&quot;2013-10-23\&quot; (optional)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Exivo\Model\AccessLogEntry[]
     */
    public function getComponentAccessLog($site_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc', $from = null, $to = null)
    {
        list($response) = $this->getComponentAccessLogWithHttpInfo($site_id, $skip, $limit, $sort, $sort_dir, $from, $to);
        return $response;
    }

    /**
     * Operation getComponentAccessLogWithHttpInfo
     *
     * get components access log
     *
     * @param  string $site_id ID of site to work (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     * @param  \DateTime $from e.g. \&quot;2013-10-22\&quot; (optional)
     * @param  \DateTime $to e.g. \&quot;2013-10-23\&quot; (optional)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Exivo\Model\AccessLogEntry[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getComponentAccessLogWithHttpInfo($site_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc', $from = null, $to = null)
    {
        $returnType = '\Exivo\Model\AccessLogEntry[]';
        $request = $this->getComponentAccessLogRequest($site_id, $skip, $limit, $sort, $sort_dir, $from, $to);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exivo\Model\AccessLogEntry[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getComponentAccessLogAsync
     *
     * get components access log
     *
     * @param  string $site_id ID of site to work (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     * @param  \DateTime $from e.g. \&quot;2013-10-22\&quot; (optional)
     * @param  \DateTime $to e.g. \&quot;2013-10-23\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getComponentAccessLogAsync($site_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc', $from = null, $to = null)
    {
        return $this->getComponentAccessLogAsyncWithHttpInfo($site_id, $skip, $limit, $sort, $sort_dir, $from, $to)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getComponentAccessLogAsyncWithHttpInfo
     *
     * get components access log
     *
     * @param  string $site_id ID of site to work (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     * @param  \DateTime $from e.g. \&quot;2013-10-22\&quot; (optional)
     * @param  \DateTime $to e.g. \&quot;2013-10-23\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getComponentAccessLogAsyncWithHttpInfo($site_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc', $from = null, $to = null)
    {
        $returnType = '\Exivo\Model\AccessLogEntry[]';
        $request = $this->getComponentAccessLogRequest($site_id, $skip, $limit, $sort, $sort_dir, $from, $to);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getComponentAccessLog'
     *
     * @param  string $site_id ID of site to work (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     * @param  \DateTime $from e.g. \&quot;2013-10-22\&quot; (optional)
     * @param  \DateTime $to e.g. \&quot;2013-10-23\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getComponentAccessLogRequest($site_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc', $from = null, $to = null)
    {
        // verify the required parameter 'site_id' is set
        if ($site_id === null || (is_array($site_id) && count($site_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $site_id when calling getComponentAccessLog'
            );
        }

        $resourcePath = '/{siteId}/accesslog/component';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($skip !== null) {
            $queryParams['skip'] = ObjectSerializer::toQueryValue($skip);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($sort !== null) {
            $queryParams['sort'] = ObjectSerializer::toQueryValue($sort);
        }
        // query params
        if ($sort_dir !== null) {
            $queryParams['sortDir'] = ObjectSerializer::toQueryValue($sort_dir);
        }
        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }

        // path params
        if ($site_id !== null) {
            $resourcePath = str_replace(
                '{' . 'siteId' . '}',
                ObjectSerializer::toPathValue($site_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getComponentAccessLogForOne
     *
     * get component's access log
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component to return (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     * @param  \DateTime $from e.g. \&quot;2013-10-22\&quot; (optional)
     * @param  \DateTime $to e.g. \&quot;2013-10-23\&quot; (optional)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Exivo\Model\AccessLogEntry[]
     */
    public function getComponentAccessLogForOne($site_id, $component_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc', $from = null, $to = null)
    {
        list($response) = $this->getComponentAccessLogForOneWithHttpInfo($site_id, $component_id, $skip, $limit, $sort, $sort_dir, $from, $to);
        return $response;
    }

    /**
     * Operation getComponentAccessLogForOneWithHttpInfo
     *
     * get component's access log
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component to return (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     * @param  \DateTime $from e.g. \&quot;2013-10-22\&quot; (optional)
     * @param  \DateTime $to e.g. \&quot;2013-10-23\&quot; (optional)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Exivo\Model\AccessLogEntry[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getComponentAccessLogForOneWithHttpInfo($site_id, $component_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc', $from = null, $to = null)
    {
        $returnType = '\Exivo\Model\AccessLogEntry[]';
        $request = $this->getComponentAccessLogForOneRequest($site_id, $component_id, $skip, $limit, $sort, $sort_dir, $from, $to);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exivo\Model\AccessLogEntry[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getComponentAccessLogForOneAsync
     *
     * get component's access log
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component to return (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     * @param  \DateTime $from e.g. \&quot;2013-10-22\&quot; (optional)
     * @param  \DateTime $to e.g. \&quot;2013-10-23\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getComponentAccessLogForOneAsync($site_id, $component_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc', $from = null, $to = null)
    {
        return $this->getComponentAccessLogForOneAsyncWithHttpInfo($site_id, $component_id, $skip, $limit, $sort, $sort_dir, $from, $to)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getComponentAccessLogForOneAsyncWithHttpInfo
     *
     * get component's access log
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component to return (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     * @param  \DateTime $from e.g. \&quot;2013-10-22\&quot; (optional)
     * @param  \DateTime $to e.g. \&quot;2013-10-23\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getComponentAccessLogForOneAsyncWithHttpInfo($site_id, $component_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc', $from = null, $to = null)
    {
        $returnType = '\Exivo\Model\AccessLogEntry[]';
        $request = $this->getComponentAccessLogForOneRequest($site_id, $component_id, $skip, $limit, $sort, $sort_dir, $from, $to);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getComponentAccessLogForOne'
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component to return (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     * @param  \DateTime $from e.g. \&quot;2013-10-22\&quot; (optional)
     * @param  \DateTime $to e.g. \&quot;2013-10-23\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getComponentAccessLogForOneRequest($site_id, $component_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc', $from = null, $to = null)
    {
        // verify the required parameter 'site_id' is set
        if ($site_id === null || (is_array($site_id) && count($site_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $site_id when calling getComponentAccessLogForOne'
            );
        }
        // verify the required parameter 'component_id' is set
        if ($component_id === null || (is_array($component_id) && count($component_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $component_id when calling getComponentAccessLogForOne'
            );
        }

        $resourcePath = '/{siteId}/accesslog/component/{componentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($skip !== null) {
            $queryParams['skip'] = ObjectSerializer::toQueryValue($skip);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($sort !== null) {
            $queryParams['sort'] = ObjectSerializer::toQueryValue($sort);
        }
        // query params
        if ($sort_dir !== null) {
            $queryParams['sortDir'] = ObjectSerializer::toQueryValue($sort_dir);
        }
        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }

        // path params
        if ($site_id !== null) {
            $resourcePath = str_replace(
                '{' . 'siteId' . '}',
                ObjectSerializer::toPathValue($site_id),
                $resourcePath
            );
        }
        // path params
        if ($component_id !== null) {
            $resourcePath = str_replace(
                '{' . 'componentId' . '}',
                ObjectSerializer::toPathValue($component_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getComponents
     *
     * get all components
     *
     * @param  string $site_id ID of site to work (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Exivo\Model\Component[]
     */
    public function getComponents($site_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc')
    {
        list($response) = $this->getComponentsWithHttpInfo($site_id, $skip, $limit, $sort, $sort_dir);
        return $response;
    }

    /**
     * Operation getComponentsWithHttpInfo
     *
     * get all components
     *
     * @param  string $site_id ID of site to work (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Exivo\Model\Component[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getComponentsWithHttpInfo($site_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc')
    {
        $returnType = '\Exivo\Model\Component[]';
        $request = $this->getComponentsRequest($site_id, $skip, $limit, $sort, $sort_dir);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exivo\Model\Component[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getComponentsAsync
     *
     * get all components
     *
     * @param  string $site_id ID of site to work (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getComponentsAsync($site_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc')
    {
        return $this->getComponentsAsyncWithHttpInfo($site_id, $skip, $limit, $sort, $sort_dir)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getComponentsAsyncWithHttpInfo
     *
     * get all components
     *
     * @param  string $site_id ID of site to work (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getComponentsAsyncWithHttpInfo($site_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc')
    {
        $returnType = '\Exivo\Model\Component[]';
        $request = $this->getComponentsRequest($site_id, $skip, $limit, $sort, $sort_dir);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getComponents'
     *
     * @param  string $site_id ID of site to work (required)
     * @param  int $skip for pagination (optional, default to 0)
     * @param  int $limit for pagination (optional, default to 0)
     * @param  string $sort for pagination (optional)
     * @param  string $sort_dir for pagination (optional, default to asc)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getComponentsRequest($site_id, $skip = '0', $limit = '0', $sort = null, $sort_dir = 'asc')
    {
        // verify the required parameter 'site_id' is set
        if ($site_id === null || (is_array($site_id) && count($site_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $site_id when calling getComponents'
            );
        }

        $resourcePath = '/{siteId}/component';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($skip !== null) {
            $queryParams['skip'] = ObjectSerializer::toQueryValue($skip);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($sort !== null) {
            $queryParams['sort'] = ObjectSerializer::toQueryValue($sort);
        }
        // query params
        if ($sort_dir !== null) {
            $queryParams['sortDir'] = ObjectSerializer::toQueryValue($sort_dir);
        }

        // path params
        if ($site_id !== null) {
            $resourcePath = str_replace(
                '{' . 'siteId' . '}',
                ObjectSerializer::toPathValue($site_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation setComponentOperatingMode
     *
     * Set operating mode of a component
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component (required)
     * @param  \Exivo\Model\SetOperatingModePayload $body body (optional)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function setComponentOperatingMode($site_id, $component_id, $body = null)
    {
        $this->setComponentOperatingModeWithHttpInfo($site_id, $component_id, $body);
    }

    /**
     * Operation setComponentOperatingModeWithHttpInfo
     *
     * Set operating mode of a component
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component (required)
     * @param  \Exivo\Model\SetOperatingModePayload $body (optional)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function setComponentOperatingModeWithHttpInfo($site_id, $component_id, $body = null)
    {
        $returnType = '';
        $request = $this->setComponentOperatingModeRequest($site_id, $component_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation setComponentOperatingModeAsync
     *
     * Set operating mode of a component
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component (required)
     * @param  \Exivo\Model\SetOperatingModePayload $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setComponentOperatingModeAsync($site_id, $component_id, $body = null)
    {
        return $this->setComponentOperatingModeAsyncWithHttpInfo($site_id, $component_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation setComponentOperatingModeAsyncWithHttpInfo
     *
     * Set operating mode of a component
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component (required)
     * @param  \Exivo\Model\SetOperatingModePayload $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setComponentOperatingModeAsyncWithHttpInfo($site_id, $component_id, $body = null)
    {
        $returnType = '';
        $request = $this->setComponentOperatingModeRequest($site_id, $component_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'setComponentOperatingMode'
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component (required)
     * @param  \Exivo\Model\SetOperatingModePayload $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function setComponentOperatingModeRequest($site_id, $component_id, $body = null)
    {
        // verify the required parameter 'site_id' is set
        if ($site_id === null || (is_array($site_id) && count($site_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $site_id when calling setComponentOperatingMode'
            );
        }
        // verify the required parameter 'component_id' is set
        if ($component_id === null || (is_array($component_id) && count($component_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $component_id when calling setComponentOperatingMode'
            );
        }

        $resourcePath = '/{siteId}/component/{componentId}/mode';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($site_id !== null) {
            $resourcePath = str_replace(
                '{' . 'siteId' . '}',
                ObjectSerializer::toPathValue($site_id),
                $resourcePath
            );
        }
        // path params
        if ($component_id !== null) {
            $resourcePath = str_replace(
                '{' . 'componentId' . '}',
                ObjectSerializer::toPathValue($component_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation unlock
     *
     * Unlock a door
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component (required)
     * @param  \Exivo\Model\UnlockPayload $body body (optional)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function unlock($site_id, $component_id, $body = null)
    {
        $this->unlockWithHttpInfo($site_id, $component_id, $body);
    }

    /**
     * Operation unlockWithHttpInfo
     *
     * Unlock a door
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component (required)
     * @param  \Exivo\Model\UnlockPayload $body (optional)
     *
     * @throws \Exivo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function unlockWithHttpInfo($site_id, $component_id, $body = null)
    {
        $returnType = '';
        $request = $this->unlockRequest($site_id, $component_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation unlockAsync
     *
     * Unlock a door
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component (required)
     * @param  \Exivo\Model\UnlockPayload $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function unlockAsync($site_id, $component_id, $body = null)
    {
        return $this->unlockAsyncWithHttpInfo($site_id, $component_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation unlockAsyncWithHttpInfo
     *
     * Unlock a door
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component (required)
     * @param  \Exivo\Model\UnlockPayload $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function unlockAsyncWithHttpInfo($site_id, $component_id, $body = null)
    {
        $returnType = '';
        $request = $this->unlockRequest($site_id, $component_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'unlock'
     *
     * @param  string $site_id ID of site to work (required)
     * @param  string $component_id ID of component (required)
     * @param  \Exivo\Model\UnlockPayload $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function unlockRequest($site_id, $component_id, $body = null)
    {
        // verify the required parameter 'site_id' is set
        if ($site_id === null || (is_array($site_id) && count($site_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $site_id when calling unlock'
            );
        }
        // verify the required parameter 'component_id' is set
        if ($component_id === null || (is_array($component_id) && count($component_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $component_id when calling unlock'
            );
        }

        $resourcePath = '/{siteId}/component/{componentId}/unlock';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($site_id !== null) {
            $resourcePath = str_replace(
                '{' . 'siteId' . '}',
                ObjectSerializer::toPathValue($site_id),
                $resourcePath
            );
        }
        // path params
        if ($component_id !== null) {
            $resourcePath = str_replace(
                '{' . 'componentId' . '}',
                ObjectSerializer::toPathValue($component_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
