<?php
/**
 * DigitalKeyPayload
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * exivo api documentation
 *
 * The exivo API lets you manage an exivo site. To be allowed to use the API the Connection service needs to be activated. For every HTTP request the `siteId`, an `API_KEY` and the corresponding `API_SECRET` are required. All this information can be found in the [exivo app](https://customer.exivo.io/credentials). A new `API_KEY` can be generated in the app. Please note that `API_SECRET` is a confidential information and should be stored securely. After closing the dialogue or refreshing the page the secret can't be displayed anymore. If the secret is lost, a new key needs to be generated and the old must be deleted.
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DigitalKeyPayload Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DigitalKeyPayload implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'digitalKeyPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'public_registration_id' => 'string',
        'mobile_app_id' => 'string',
        'mobile_app_name' => 'string',
        'form_factor' => 'string',
        'install_notification' => 'bool',
        'callback_uri' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'public_registration_id' => null,
        'mobile_app_id' => null,
        'mobile_app_name' => null,
        'form_factor' => null,
        'install_notification' => null,
        'callback_uri' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'public_registration_id' => 'publicRegistrationId',
        'mobile_app_id' => 'mobileAppId',
        'mobile_app_name' => 'mobileAppName',
        'form_factor' => 'formFactor',
        'install_notification' => 'installNotification',
        'callback_uri' => 'callbackUri'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'public_registration_id' => 'setPublicRegistrationId',
        'mobile_app_id' => 'setMobileAppId',
        'mobile_app_name' => 'setMobileAppName',
        'form_factor' => 'setFormFactor',
        'install_notification' => 'setInstallNotification',
        'callback_uri' => 'setCallbackUri'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'public_registration_id' => 'getPublicRegistrationId',
        'mobile_app_id' => 'getMobileAppId',
        'mobile_app_name' => 'getMobileAppName',
        'form_factor' => 'getFormFactor',
        'install_notification' => 'getInstallNotification',
        'callback_uri' => 'getCallbackUri'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const FORM_FACTOR_PHONE = 'ma-phone';
    const FORM_FACTOR_EMAIL = 'ma-email';
    const FORM_FACTOR_CUSTOM = 'ma-custom';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFormFactorAllowableValues()
    {
        return [
            self::FORM_FACTOR_PHONE,
            self::FORM_FACTOR_EMAIL,
            self::FORM_FACTOR_CUSTOM,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['public_registration_id'] = isset($data['public_registration_id']) ? $data['public_registration_id'] : null;
        $this->container['mobile_app_id'] = isset($data['mobile_app_id']) ? $data['mobile_app_id'] : null;
        $this->container['mobile_app_name'] = isset($data['mobile_app_name']) ? $data['mobile_app_name'] : null;
        $this->container['form_factor'] = isset($data['form_factor']) ? $data['form_factor'] : null;
        $this->container['install_notification'] = isset($data['install_notification']) ? $data['install_notification'] : null;
        $this->container['callback_uri'] = isset($data['callback_uri']) ? $data['callback_uri'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['public_registration_id'] === null) {
            $invalidProperties[] = "'public_registration_id' can't be null";
        }
        if ($this->container['mobile_app_id'] === null) {
            $invalidProperties[] = "'mobile_app_id' can't be null";
        }
        if (!preg_match("/^[0-9]*$/", $this->container['mobile_app_id'])) {
            $invalidProperties[] = "invalid value for 'mobile_app_id', must be conform to the pattern /^[0-9]*$/.";
        }

        if ($this->container['form_factor'] === null) {
            $invalidProperties[] = "'form_factor' can't be null";
        }
        $allowedValues = $this->getFormFactorAllowableValues();
        if (!is_null($this->container['form_factor']) && !in_array($this->container['form_factor'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'form_factor', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets public_registration_id
     *
     * @return string
     */
    public function getPublicRegistrationId()
    {
        return $this->container['public_registration_id'];
    }

    /**
     * Sets public_registration_id
     *
     * @param string $public_registration_id public_registration_id
     *
     * @return $this
     */
    public function setPublicRegistrationId($public_registration_id)
    {
        $this->container['public_registration_id'] = $public_registration_id;

        return $this;
    }

    /**
     * Gets mobile_app_id
     *
     * @return string
     */
    public function getMobileAppId()
    {
        return $this->container['mobile_app_id'];
    }

    /**
     * Sets mobile_app_id
     *
     * @param string $mobile_app_id mobile_app_id
     *
     * @return $this
     */
    public function setMobileAppId($mobile_app_id)
    {

        if ((!preg_match("/^[0-9]*$/", $mobile_app_id))) {
            throw new \InvalidArgumentException("invalid value for $mobile_app_id when calling DigitalKeyPayload., must conform to the pattern /^[0-9]*$/.");
        }

        $this->container['mobile_app_id'] = $mobile_app_id;

        return $this;
    }

    /**
     * Gets mobile_app_name
     *
     * @return string
     */
    public function getMobileAppName()
    {
        return $this->container['mobile_app_name'];
    }

    /**
     * Sets mobile_app_name
     *
     * @param string $mobile_app_name mobile_app_name
     *
     * @return $this
     */
    public function setMobileAppName($mobile_app_name)
    {
        $this->container['mobile_app_name'] = $mobile_app_name;

        return $this;
    }

    /**
     * Gets form_factor
     *
     * @return string
     */
    public function getFormFactor()
    {
        return $this->container['form_factor'];
    }

    /**
     * Sets form_factor
     *
     * @param string $form_factor form_factor
     *
     * @return $this
     */
    public function setFormFactor($form_factor)
    {
        $allowedValues = $this->getFormFactorAllowableValues();
        if (!in_array($form_factor, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'form_factor', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['form_factor'] = $form_factor;

        return $this;
    }

    /**
     * Gets install_notification
     *
     * @return bool
     */
    public function getInstallNotification()
    {
        return $this->container['install_notification'];
    }

    /**
     * Sets install_notification
     *
     * @param bool $install_notification install_notification
     *
     * @return $this
     */
    public function setInstallNotification($install_notification)
    {
        $this->container['install_notification'] = $install_notification;

        return $this;
    }

    /**
     * Gets callback_uri
     *
     * @return string
     */
    public function getCallbackUri()
    {
        return $this->container['callback_uri'];
    }

    /**
     * Sets callback_uri
     *
     * @param string $callback_uri callback_uri
     *
     * @return $this
     */
    public function setCallbackUri($callback_uri)
    {
        $this->container['callback_uri'] = $callback_uri;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


