<?php
/**
 * DigitalKeyVisitTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Exivo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * exivo api documentation
 *
 * The exivo API lets you manage an exivo site. To be allowed to use the API the Connection service needs to be activated. For every HTTP request the `siteId`, an `API_KEY` and the corresponding `API_SECRET` are required. All this information can be found in the [exivo app](https://customer.exivo.io/credentials). A new `API_KEY` can be generated in the app. Please note that `API_SECRET` is a confidential information and should be stored securely. After closing the dialogue or refreshing the page the secret can't be displayed anymore. If the secret is lost, a new key needs to be generated and the old must be deleted.
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Exivo;

/**
 * DigitalKeyVisitTest Class Doc Comment
 *
 * @category    Class
 * @description DigitalKeyVisit
 * @package     Exivo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DigitalKeyVisitTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DigitalKeyVisit"
     */
    public function testDigitalKeyVisit()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "expired"
     */
    public function testPropertyExpired()
    {
    }

    /**
     * Test attribute "revoked"
     */
    public function testPropertyRevoked()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "valid_from"
     */
    public function testPropertyValidFrom()
    {
    }

    /**
     * Test attribute "valid_to"
     */
    public function testPropertyValidTo()
    {
    }

    /**
     * Test attribute "components"
     */
    public function testPropertyComponents()
    {
    }

    /**
     * Test attribute "form_factor"
     */
    public function testPropertyFormFactor()
    {
    }

    /**
     * Test attribute "public_registration_id"
     */
    public function testPropertyPublicRegistrationId()
    {
    }

    /**
     * Test attribute "mobile_app"
     */
    public function testPropertyMobileApp()
    {
    }

    /**
     * Test attribute "install_notification"
     */
    public function testPropertyInstallNotification()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "callback_uri"
     */
    public function testPropertyCallbackUri()
    {
    }
}
